added solution
mate-academy/jv-web-servlet-lifecycle pull request #27
Opened 2021-05-20 14:29 UTC by anatolii-zarytskyi

2021-05-20 14:35 UTC, freedmanMain requested changes

2021-05-20 14:35 UTC, freedmanMain commented on src/main/java/mate/controller/IndexController.java
> +        myResource = MyCoolResource.openResource();
Additionally, you must call the init() method here first.

2021-05-20 14:35 UTC, freedmanMain commented on src/main/java/mate/controller/IndexController.java
> +        myResource.close();
Same here, but at the end.

2021-05-20 14:39 UTC, freedmanMain approved these changes

2021-05-21 05:19 UTC, RomanDubovskyi approved these changes

2022-12-30 18:44 UTC, closed without merging